# API 1

# SCENARIO 1
GET http://localhost:3000/todos/?status=TO%20DO

###
# SCENARIO 2
GET http://localhost:3000/todos/?priority=HIGH



###
# SCENARIO 3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

# SCENARIO 4
GET http://localhost:3000/todos/?search_q=Buy

###

# SCENARIO 5
GET http://localhost:3000/todos/?category=WORK&status=DONE

###

# SCENARIO 6
GET http://localhost:3000/todos/?category=HOME

###

# SCENARIO 7

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###

# API 2

GET http://localhost:3000/todos/1/